### ISSUE TITLE
Java to EDI Example

### ISSUE THREAD

**Issue by warefhaque** [smooks/smooks-examples#160]
## Problem
- I am able toe convert EDI to Java objects
- I need to convert from the same Java model to EDI String
- What is the recommended approach for this? 
  - Is it to convert the java object to xml and then pass that xml to `edi:unparser`?  Any recommendations on how to generate the xml in that case? 

## Approaches I've tried
- Pass the JavaObject directly into an `edi:unparser`
```
<smooks-resource-list xmlns="https://www.smooks.org/xsd/smooks-2.0.xsd"
    xmlns:edi="https://www.smooks.org/xsd/smooks/edi-2.0.xsd"
    xmlns:core="https://www.smooks.org/xsd/smooks/smooks-core-1.6.xsd">

  <core:smooks filterSourceOn="/Hcfa">
    <core:action>
      <core:inline>
        <core:replace/>
      </core:inline>
    </core:action>
    <core:config>
      <smooks-resource-list>
        <edi:unparser unparseOnElement="*"
            schemaURI="/hcfa-edi-to-java-mapping.dfdl.xsd"
            dataElementSeparator="*"
            segmentTerminator="%NL;" compositeDataElementSeparator="^"/>
      </smooks-resource-list>
    </core:config>
  </core:smooks>
</smooks-resource-list>
```
Doesn't work as as the `xml` generated from the JavaObject has the class package as primary element and field names as the children while the schema is looking for `/Hcfa` element 

- Try to create an xml that matches `/hcfa-edi-to-java-mapping.dfdl.xsd` i.e. the xml schema I used to parse the EDI in the first place.  I tried this using `XMLBinding` class from Smooks with a binding by following the bindings from [xml-read-write-transform](https://github.com/smooks/smooks/tree/v1.7.1/smooks-examples/xml-read-write-transform) example. The issue here is that the binding does not create the xml elements from the java object in order thats defined in the schema and the `edi:unparser` above fails.

**Comment by jeffgbradley2** [comment]
I experienced the same problem and haven't been able to find a solution. The smooks edi:unparser doesn't appear to be a good solution for generating ANSI X12 EDI for the reasons you already mentioned. The only way for it to be feasible in my use case is to pass a java map to Freemarker to produce XML in the exact sequence expected by the DFDL schema. However, it is easier to just use Freemarker or some other method to produce the EDI directly IMO.

**Comment by warefhaque** [comment]
I see. Thinking of using [Jackson](https://github.com/FasterXML/jackson-dataformat-xml) for the Java <-> XML segment instead of JAXB and smooks unparser for the XML <->  EDI segment. Do you guys foresee any issues I may have with this approach?

**Comment by claudemamo** [comment]
>Do you guys foresee any issues I may have with this approach?

If it works no ;-).
