### ISSUE TITLE
Add dependency to javax.annotation

### ISSUE THREAD

**Issue by robertmarkbram** [smooks/smooks-examples#163]
Hi All,

When running

```
mvn clean install
```

On [java-to-xml](https://github.com/smooks/smooks-examples/tree/master/java-to-xml), I was getting test failures from:

```
JavaTransformTest.test:66 » NoClassDefFound javax/annotation/Resource
```

I needed to edit `smooks-examples\pom.xml` and add this dependency:

```xml
<!-- https://mvnrepository.com/artifact/javax.annotation/javax.annotation-api -->
<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.3.2</version>
</dependency>
```

Source: https://stackoverflow.com/a/48238319/257233

Rob
:)

**Comment by claudemamo** [comment]
I couldn't reproduce the error locally and the build is passing on GitHub Actions. Which version of Java are you running it on? Smooks 2 is tested on Java 8.

**Comment by MatthiasBergen** [comment]
> Hi All,
> 
> When running
> 
> ```
> mvn clean install
> ```
> 
> On [java-to-xml](https://github.com/smooks/smooks-examples/tree/master/java-to-xml), I was getting test failures from:
> 
> ```
> JavaTransformTest.test:66 » NoClassDefFound javax/annotation/Resource
> ```
> 
> I needed to edit `smooks-examples\pom.xml` and add this dependency:
> 
> ```
> 
> <dependency>
>     <groupId>javax.annotation</groupId>
>     <artifactId>javax.annotation-api</artifactId>
>     <version>1.3.2</version>
> </dependency>
> ```
> 
> Source: https://stackoverflow.com/a/48238319/257233
> 
> Rob :)

Thank you! Had the same problem running `mvn clean install` on the sample "edifact-to-xml". Adding the dependency fixed it for me!
