### ISSUE TITLE
Programmatic way to register a TypeConverterFactory?

### ISSUE THREAD

**Issue by robertmarkbram** [smooks/smooks-examples#165]
I have seen in the [csv-to-java-programmatic](https://github.com/smooks/smooks-examples/tree/master/csv-to-java-programmatic) example that it needs a [org.smooks.api.converter.TypeConverterFactory](https://github.com/smooks/smooks-examples/blob/master/csv-to-java-programmatic/src/main/resources/META-INF/services/org.smooks.api.converter.TypeConverterFactory) file in `META-INF` to register a custom `TypeConverterFactory`.

How does this work exactly? I see that the `META-INF` folder is mentioned a few times in the [Smooks V2 documentation](https://www.smooks.org/v2/documentation/), but I couldn't see anything linking that to `TypeConverterFactory`.

Is there no way to do this programmatically?

Rob
:)

**Comment by claudemamo** [comment]
>Is there no way to do this programmatically?

There is. Here's an example of registering a `TypeConverter` that turns an `Orange` into an `Apple`:

```java
((Set<TypeConverterFactory<?, ?>>) smooks.getApplicationContext().getRegistry().lookup(TypeConverterFactoryLookup.TYPE_CONVERTER_FACTORY_REGISTRY_KEY)).add(new TypeConverterFactory<Orange, Apple>() {

            @Override
            public TypeConverter<Orange, Apple> createTypeConverter() {
                return new TypeConverter<Orange, Apple>() {
                    @Override
                    public Appe convert(Orange value) {
                        // write the code to turn an orange into an apple
                        return null;
                    }
                };
            }

            @Override
            public TypeConverterDescriptor<Class<Orange>, Class<Apple>> getTypeConverterDescriptor() {
                return new TypeConverterDescriptor<Class<Orange>, Class<Apple>>() {
                    @Override
                    public Class<Orange> getSourceType() {
                        return Orange.class;
                    }

                    @Override
                    public Class<Apple> getTargetType() {
                        return Apple.class;
                    }

                    @Override
                    public Short getPriority() {
                        return 1;
                    }
                };
            }
        });
```
